os: Visual Studio 2017

# version format
version: 2.0.0.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta 
  - set APPVEYOR_REPO_TAG=true

# to disable automatic builds
build_script:
  - cd BuildPackage
  - Build.bat

artifacts:
  - path: BuildPackage\artifacts\*.nupkg
  - path: BuildPackage\artifacts\*.zip

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/hifiagency/api/v2/package
    symbol_server: https://www.myget.org/F/hifiagency/symbols/api/v2/package
    api_key:
      secure: a83Z0hBpBzA7FP6WdMtb6RgvXSzUjU/giPFVH/PPGaJIac1cfXh1f74M+Q+ftfws
    artifact: /.*\.nupkg/
    on:
      branch: master
