# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
- dev

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  packageSuffix: 'beta'
  version: '2.0.2'
  ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
    revision: $[ counter('.', 0) ]
    separator: '.'
  ${{ if eq( variables['Build.SourceBranchName'], 'master') }}:
    revision: ''
    separator: ''

name: $(version)$(separator)$(revision)

steps:
- task: Assembly-Info-NetFramework@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **\AssemblyInfo.cs

      **\AssemblyInfo.vb
    InsertAttributes: false
    FileEncoding: 'auto'
    WriteBOM: false
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: CmdLine@2
  displayName: Install umbpack
  inputs:
    script: 'dotnet tool install --global Umbraco.Tools.Packages'

- task: CmdLine@2
  displayName: Umbpack pack
  inputs:
    script: 'umbpack pack HiFi.PositionalContent.umb.xml -o $(Build.ArtifactStagingDirectory) -v $(Build.BuildNumber)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'HiFi.PositionalContent.nuspec'
    versioningScheme: 'byBuildNumber'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'HiFi.PositionalContent.Core.nuspec'
    versioningScheme: 'byBuildNumber'    
  
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '2da32941-9b33-449c-ae98-69ead285ebf1/c6702797-d178-4071-86d1-88c556b7ba05'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
